/* Cargill and ADM US grain buying points, from public bid listings.
   `sites.json` is generated by data-source/build.js — edit there, not here.
   Row shape: [co, name, state, lat, lon, type, region, crops]; letter codes are
   translated to the readable values in src/map/objects/buying-point.ts here. */
import raw from "./sites.json"
import type { BuyingPoint, Company, Crop, Facility } from "@app/map/objects/buying-point"

export type { Crop }

export const CROP: Record<Crop, string> = {
  c: "Corn",
  s: "Soybeans",
  w: "Wheat",
  m: "Sorghum",
  o: "Canola, sunflower",
}

/** Crops that have a Kernel commodity hue (decision 0013). */
export const COMMODITY_OF: Partial<Record<Crop, "corn" | "soybeans" | "wheat" | "canola">> = {
  c: "corn",
  s: "soybeans",
  w: "wheat",
  o: "canola",
}

const CO: Record<string, Company> = { C: "cargill", A: "adm" }
const TYPE: Record<string, Facility> = { r: "river", i: "elevator", p: "processor", x: "export" }
type Row = [string, string, string, number, number, string, string, string]

const seen = new Map<string, number>()
export const SITES: BuyingPoint[] = (raw as Row[]).map(([co, name, state, lat, lon, type, region, crops], id) => {
  const key = `${lat},${lon}`
  const stack = seen.get(key) ?? 0
  seen.set(key, stack + 1)
  return { id, co: CO[co], name, state, lat, lon, type: TYPE[type], region, crops: [...crops] as Crop[], stack }
})

export const cropList = (crops: Crop[]) => crops.map((c) => CROP[c].toLowerCase()).join(", ")
