/* Cargill and ADM US grain buying points, from public bid listings.
   `sites.json` is generated by data-source/build.js — edit there, not here.
   Row shape: [co, name, state, lat, lon, type, region, crops]. */
import raw from "./sites.json"

export type Company = "C" | "A"
export type FacilityType = "r" | "i" | "p" | "x"
export type Crop = "c" | "s" | "w" | "m" | "o"

export interface Site {
  id: number
  co: Company
  name: string
  state: string
  lat: number
  lon: number
  type: FacilityType
  region: string
  crops: Crop[]
  /** Index among sites sharing the same town centroid; used to fan markers out. */
  stack: number
}

export const COMPANY: Record<Company, string> = { C: "Cargill", A: "ADM" }

export const FACILITY: Record<FacilityType, { label: string; plural: string }> = {
  r: { label: "River terminal", plural: "River terminals" },
  i: { label: "Interior elevator", plural: "Interior elevators" },
  p: { label: "Processing plant", plural: "Processing plants" },
  x: { label: "Export terminal", plural: "Export terminals" },
}

export const CROP: Record<Crop, string> = {
  c: "Corn",
  s: "Soybeans",
  w: "Wheat",
  m: "Sorghum",
  o: "Canola, sunflower",
}

/** Crops that have a Kernel commodity hue (decision 0013). */
export const COMMODITY_OF: Partial<Record<Crop, "corn" | "soybeans" | "wheat" | "canola">> = {
  c: "corn",
  s: "soybeans",
  w: "wheat",
  o: "canola",
}

type Row = [Company, string, string, number, number, FacilityType, string, string]

const seen = new Map<string, number>()
export const SITES: Site[] = (raw as Row[]).map(([co, name, state, lat, lon, type, region, crops], id) => {
  const key = `${lat},${lon}`
  const stack = seen.get(key) ?? 0
  seen.set(key, stack + 1)
  return { id, co, name, state, lat, lon, type, region, crops: [...crops] as Crop[], stack }
})

export const siteLabel = (s: Site) => `${COMPANY[s.co]} ${s.name}, ${s.state}`
export const cropList = (crops: Crop[]) => crops.map((c) => CROP[c].toLowerCase()).join(", ")
