/* Generated by packages/catalog/scripts/generate-portal-adapter.mjs. Do not edit directly. */
import { catalog, selectPortalLifecycleMeta } from "@kernel/catalog"

export const componentMeta = selectPortalLifecycleMeta(catalog)
export const components = componentMeta.filter((entity) => entity.group === "component")
