import { existsSync, readFileSync } from "node:fs"

export const PROTOTYPE_STATUS_PATH = "docs/prototypes/status.md"
export const FIGMA_MAP_PATH = "docs/figma/figma-map.json"

function ordered(value, preferred = []) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return value
  const result = {}
  for (const key of preferred) if (key in value) result[key] = value[key]
  for (const key of Object.keys(value).sort()) if (!(key in result)) result[key] = value[key]
  return result
}

function orderedFigmaEntry(entry) {
  const result = ordered(entry, ["nodeId", "nodeName", "key", "section", "kind", "page", "status", "props", "children", "note", "nodes"])
  if (result.children) {
    result.children = Object.fromEntries(Object.entries(result.children).map(([name, child]) => [name, ordered(child, ["nodeId", "key", "axes", "props", "note"])]))
  }
  return result
}

export function projectFigmaMap(registry) {
  const compatibility = registry.figma?.compatibility
  if (!compatibility) throw new Error("Registry is missing figma.compatibility metadata")
  const entities = {}
  for (const initiative of registry.initiatives) {
    for (const surface of initiative.surfaces?.figma ?? []) {
      if (!surface.mapEntry) continue
      if (initiative.entityIds.length !== 1) throw new Error(`Figma map initiative ${initiative.id} must identify exactly one entity`)
      entities[initiative.entityIds[0]] = orderedFigmaEntry(surface.mapEntry)
      break
    }
  }
  return {
    file: compatibility.file,
    collections: compatibility.collections,
    pages: compatibility.pages,
    entities,
    libraries: compatibility.libraries,
    notes: compatibility.notes,
  }
}

export function renderFigmaMap(registry) {
  return JSON.stringify(projectFigmaMap(registry), null, 2)
}

function evidenceLinks(concern) {
  const links = new Set()
  for (const entry of concern.history ?? []) for (const value of entry.evidence ?? []) links.add(value)
  if (concern.migrationImport?.sourcePath) links.add(concern.migrationImport.sourcePath)
  if (concern.acceptance?.path) links.add(concern.acceptance.path)
  if (concern.canonical?.sourcePath) links.add(concern.canonical.sourcePath)
  return [...links].sort()
}

export function renderPrototypeStatus(registry) {
  const lines = [
    "# Prototype status",
    "",
    "> Generated by `npm run ds:generate`. Do not edit by hand.",
    "",
  ]
  if (registry.initiatives.length === 0) {
    lines.push("No prototype initiatives are registered.", "")
    return lines.join("\n")
  }
  for (const initiative of [...registry.initiatives].sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`## ${initiative.title}`, "", `- ID: \`${initiative.id}\``, `- Lifecycle: \`${initiative.lifecycle}\``, `- Scope: \`${initiative.scopeKey}\``, `- Entities: ${initiative.entityIds.map((id) => `\`${id}\``).join(", ")}`)
    const surfaces = []
    if (initiative.surfaces?.figma?.length) surfaces.push(`Figma (${initiative.surfaces.figma.length})`)
    if (initiative.surfaces?.kernelApp?.length) surfaces.push(`kernel-app (${initiative.surfaces.kernelApp.length})`)
    lines.push(`- Surfaces: ${surfaces.join(", ") || "none"}`, "", "| Concern | State | Origin | Canonical owner | Blocker | Evidence |", "| --- | --- | --- | --- | --- | --- |")
    for (const concern of [...initiative.concerns].sort((a, b) => a.concern.localeCompare(b.concern))) {
      const blocker = concern.migrationImport?.evidenceGap ?? (concern.state === "validated" ? "Awaiting explicit acceptance and committed canonical evidence." : "—")
      const evidence = evidenceLinks(concern).map((value) => `\`${value}\``).join("<br>") || "—"
      lines.push(`| ${concern.concern} | ${concern.state} | ${concern.origin} | ${concern.canonical?.package ?? "—"} | ${blocker} | ${evidence} |`)
    }
    lines.push("")
  }
  return lines.join("\n")
}

function checkProjection(path, expected, command) {
  if (!existsSync(path)) return { ok: false, expected, message: `${path} is missing` }
  const actual = readFileSync(path, "utf8").replaceAll("\r\n", "\n")
  return actual === expected
    ? { ok: true, expected }
    : { ok: false, expected, message: `${path} is stale; run ${command}` }
}

export function checkPrototypeProjection(path, registry) {
  return checkProjection(path, renderPrototypeStatus(registry), "npm run ds:generate")
}

export function checkFigmaProjection(path, registry) {
  return checkProjection(path, renderFigmaMap(registry), "npm run ds:generate")
}
