import { existsSync, readFileSync } from "node:fs"

export const PROTOTYPE_STATUS_PATH = "docs/prototypes/status.md"

export function renderPrototypeStatus(registry) {
  const lines = [
    "# Prototype status",
    "",
    "> Generated by `npm run ds:prototype -- project`. Do not edit by hand.",
    "",
  ]
  if (registry.initiatives.length === 0) {
    lines.push("No prototype initiatives are registered.", "")
    return lines.join("\n")
  }
  for (const initiative of [...registry.initiatives].sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`## ${initiative.title}`, "", `- ID: \`${initiative.id}\``, `- Lifecycle: \`${initiative.lifecycle}\``, `- Scope: \`${initiative.scopeKey}\``, `- Entities: ${initiative.entityIds.map((id) => `\`${id}\``).join(", ")}`)
    const surfaces = []
    if (initiative.surfaces?.figma?.length) surfaces.push(`Figma (${initiative.surfaces.figma.length})`)
    if (initiative.surfaces?.kernelApp?.length) surfaces.push(`kernel-app (${initiative.surfaces.kernelApp.length})`)
    lines.push(`- Surfaces: ${surfaces.join(", ") || "none"}`, "", "| Concern | State | Origin | Canonical owner |", "| --- | --- | --- | --- |")
    for (const concern of [...initiative.concerns].sort((a, b) => a.concern.localeCompare(b.concern))) {
      lines.push(`| ${concern.concern} | ${concern.state} | ${concern.origin} | ${concern.canonical?.package ?? "—"} |`)
    }
    lines.push("")
  }
  return lines.join("\n")
}

export function checkPrototypeProjection(path, registry) {
  const expected = renderPrototypeStatus(registry)
  if (!existsSync(path)) return { ok: false, expected, message: `${path} is missing` }
  const actual = readFileSync(path, "utf8").replaceAll("\r\n", "\n")
  return actual === expected
    ? { ok: true, expected }
    : { ok: false, expected, message: `${path} is stale; run npm run ds:prototype -- project` }
}
