import { readFile, readdir, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { componentMeta } from "../src/lib/component-meta.ts"

const portalRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const repoRoot = resolve(portalRoot, "..")
const docsDir = resolve(portalRoot, "src/lib/component-docs")
const compositionFile = resolve(portalRoot, "src/lib/objects/composition.ts")
const outputArgument = process.argv[2]
const outputFile = outputArgument ? resolve(process.cwd(), outputArgument) : resolve(repoRoot, "packages/catalog/src/entities.ts")

function slugify(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

function readString(source, key) {
  return source.match(new RegExp(`\\b${key}:\\s*[\"']([^\"']+)[\"']`))?.[1]
}

function readStringArray(source, key) {
  const body = source.match(new RegExp(`\\b${key}:\\s*\\[([\\s\\S]*?)\\]`))?.[1]
  return body ? [...body.matchAll(/["']([^"']+)["']/g)].map((match) => match[1]) : []
}

function resolveSourceFile(sourceFile) {
  if (sourceFile.startsWith("marks/")) return `kernel-portal/src/components/ui/${sourceFile}`
  if (sourceFile.includes("/")) return `kernel-portal/src/${sourceFile}`
  return `kernel-portal/src/components/ui/${sourceFile}`
}

async function readDocRecords() {
  const barrelSource = await readFile(resolve(docsDir, "index.ts"), "utf8")
  const registeredFiles = new Set([...barrelSource.matchAll(/from ["']\.\/([^"']+\.ts)["']/g)].map((match) => match[1]))
  registeredFiles.delete("schema.ts")
  const availableFiles = new Set(await readdir(docsDir))
  const files = [...registeredFiles].sort()
  const records = []

  for (const file of files) {
    if (!availableFiles.has(file)) throw new Error(`Docs barrel references missing file ${file}`)
    const source = await readFile(resolve(docsDir, file), "utf8")
    const name = readString(source, "name")
    const slug = readString(source, "slug")
    if (!name || !slug) continue
    records.push({
      name,
      normalizedName: slugify(name),
      slug,
      kind: source.match(/metadata:\s*\{[^}]*kind:\s*["']([^"']+)["']/)?.[1],
      sourceFile: `kernel-portal/src/lib/component-docs/${file}`,
      sourceFiles: readStringArray(source, "sourceFiles").map(resolveSourceFile),
    })
  }

  return records
}

const docs = await readDocRecords()
const docsByName = new Map(docs.map((doc) => [doc.normalizedName, doc]))
const docsBySlug = new Map(docs.map((doc) => [doc.slug, doc]))
const aliases = new Map([["resizable", "scroll-area"]])

const compositionSource = await readFile(compositionFile, "utf8")
for (const requiredExport of ["primitives", "regions", "rules"]) {
  if (!new RegExp(`export const ${requiredExport}\\b`).test(compositionSource)) {
    throw new Error(`Composition contract is missing export ${requiredExport}`)
  }
}

const patternDocs = new Set(docs.filter((doc) => doc.kind === "pattern").map((doc) => doc.slug))
for (const meta of componentMeta.filter((entity) => entity.group === "pattern")) {
  if (!patternDocs.has(slugify(meta.name))) {
    throw new Error(`Pattern ${meta.name} is missing a pattern documentation entity`)
  }
}

const entities = componentMeta.map((meta) => {
  const normalizedName = slugify(meta.name)
  const doc = docsByName.get(normalizedName) ?? docsBySlug.get(aliases.get(normalizedName))
  const capabilities = []
  if (doc) capabilities.push("documented")
  if (meta.a11y === "reviewed") capabilities.push("accessibility-reviewed")
  if (meta.group === "object") capabilities.push("composition-contract")

  return {
    id: `${meta.group}.${normalizedName}`,
    name: meta.name,
    kind: meta.group,
    maturity: meta.maturity,
    accessibility: meta.a11y,
    package: "kernel-portal",
    tags: [meta.group, meta.maturity],
    capabilities,
    relationships: [],
    documentation: {
      ...(doc ? { slug: doc.slug, sourceFile: doc.sourceFile } : {}),
      portalAnchor: meta.anchor,
    },
    ai: {
      bundleCategory: meta.group === "component" ? "general" : "design",
      guidanceSource: doc ? "component-docs" : meta.group === "object" ? "composition-contract" : "lifecycle-metadata",
    },
    sourceFiles: doc?.sourceFiles ?? [],
    ...(meta.note ? { note: meta.note } : {}),
  }
})

const output = `/* Generated by kernel-portal/scripts/migrate-catalog.mjs. Do not edit directly. */\nimport type { CatalogEntity } from "./schema.ts"\n\nexport const catalog = ${JSON.stringify(entities, null, 2)} as const satisfies readonly CatalogEntity[]\n`
await writeFile(outputFile, output)
console.log(`Generated ${entities.length} catalog entities (${entities.filter((entity) => entity.documentation.slug).length} documented).`)
