import type { ObjectModel, ObjectRow } from "./types.ts"

/**
 * Contract — the anchor object of the grain-buying merchant platform.
 * A durable agreement between the house and a counterparty to move a
 * specific commodity, quantity, and price over a delivery window.
 * Settlements reference the contract they close.
 */
export const contractModel: ObjectModel = {
  key: "contract",
  label: "Contract",
  plural: "Contracts",
  fields: [
    { key: "id", label: "Contract #", type: "text", sample: "K-24081" },
    { key: "counterparty", label: "Counterparty", type: "text", sample: "Prairie Grain Co." },
    { key: "commodity", label: "Commodity", type: "text", sample: "corn" },
    { key: "quantity", label: "Quantity (bu)", type: "number", sample: 25000 },
    { key: "unitPrice", label: "Unit price", type: "money", sample: 4.72 },
    { key: "deliveryStart", label: "Delivery start", type: "date", sample: "2026-08-01" },
    { key: "deliveryEnd", label: "Delivery end", type: "date", sample: "2026-08-31" },
    { key: "status", label: "Status", type: "status", sample: "active" },
    { key: "notes", label: "Notes", type: "text", sample: "" },
  ],
  statuses: [
    { key: "draft", label: "Draft", tone: "draft" },
    { key: "active", label: "Active", tone: "active" },
    { key: "settled", label: "Settled", tone: "success" },
    { key: "cancelled", label: "Cancelled", tone: "danger" },
  ],
  associations: [
    { key: "settlements", label: "Settlements", targetObjectKey: "settlement" },
  ],
}

export const contractRows: ObjectRow[] = [
  {
    id: "K-24081",
    coord: { x: 22, y: 18 },
    counterparty: "Prairie Grain Co.",
    commodity: "corn",
    quantity: 25000,
    unitPrice: 4.72,
    deliveryStart: "2026-08-01",
    deliveryEnd: "2026-08-31",
    status: "active",
    notes: "Rail delivery, Kansas City.",
  },
  {
    id: "K-24082",
    coord: { x: 41, y: 27 },
    counterparty: "Midwest Ag Trust",
    commodity: "soy",
    quantity: 18500,
    unitPrice: 11.15,
    deliveryStart: "2026-07-15",
    deliveryEnd: "2026-08-15",
    status: "settled",
    notes: "",
  },
  {
    id: "K-24083",
    coord: { x: 58, y: 12 },
    counterparty: "North Plains Elevator",
    commodity: "wheat",
    quantity: 32000,
    unitPrice: 6.04,
    deliveryStart: "2026-09-01",
    deliveryEnd: "2026-09-30",
    status: "draft",
    notes: "Awaiting counterparty signature.",
  },
  {
    id: "K-24084",
    coord: { x: 73, y: 44 },
    counterparty: "Boreal Canola Ltd.",
    commodity: "canola",
    quantity: 12000,
    unitPrice: 14.88,
    deliveryStart: "2026-10-01",
    deliveryEnd: "2026-10-31",
    status: "active",
    notes: "",
  },
  {
    id: "K-24085",
    coord: { x: 34, y: 61 },
    counterparty: "Prairie Grain Co.",
    commodity: "corn",
    quantity: 15000,
    unitPrice: 4.68,
    deliveryStart: "2026-08-10",
    deliveryEnd: "2026-08-25",
    status: "cancelled",
    notes: "Counterparty defaulted.",
  },
  {
    id: "K-24086",
    coord: { x: 51, y: 78 },
    counterparty: "River Valley Farms",
    commodity: "soy",
    quantity: 22000,
    unitPrice: 11.32,
    deliveryStart: "2026-07-20",
    deliveryEnd: "2026-08-20",
    status: "settled",
    notes: "",
  },
  {
    id: "K-24087",
    coord: { x: 68, y: 82 },
    counterparty: "Golden Fields Coop",
    commodity: "wheat",
    quantity: 28000,
    unitPrice: 5.98,
    deliveryStart: "2026-09-05",
    deliveryEnd: "2026-10-05",
    status: "active",
    notes: "Delivery split across two elevators.",
  },
  {
    id: "K-24088",
    coord: { x: 86, y: 55 },
    counterparty: "Boreal Canola Ltd.",
    commodity: "canola",
    quantity: 9500,
    unitPrice: 15.02,
    deliveryStart: "2026-11-01",
    deliveryEnd: "2026-11-15",
    status: "draft",
    notes: "",
  },
]
